name: 🚀 Add a New Skill
description: Submit a new MoltBot skill to be listed in the directory
title: "[SKILL]: "
labels: ["new-skill"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a skill! Please fill out the form below.
  
  - type: input
    id: skill_name
    attributes:
      label: Skill Name
      placeholder: e.g., "YouTube Summarizer"
    validations:
      required: true
  
  - type: input
    id: repo_url
    attributes:
      label: GitHub Repository URL
      description: Must be a public GitHub repository
      placeholder: https://github.com/user/repo
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose the most appropriate category for this skill
      options:
        - Web & Frontend Development
        - Coding Agents & IDEs
        - Git & GitHub
        - DevOps & Cloud
        - Browser & Automation
        - Image & Video Generation
        - Apple Apps & Services
        - Search & Research
        - Clawdbot Tools
        - CLI Utilities
        - iOS & macOS Development
        - Marketing & Sales
        - Productivity & Tasks
        - AI & LLMs
        - Finance & Crypto
        - Media & Streaming
        - Notes & PKM
        - Transportation
        - Personal Development
        - Health & Fitness
        - Communication
        - Speech & Transcription
        - Smart Home & IoT
        - Shopping & E-commerce
        - Calendar & Scheduling
        - PDF & Documents
        - Self-Hosted & Automation
        - News & RSS
        - Bookmarks & Reading
        - Weather
        - Security & Passwords
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Short Description
      description: One-sentence description of what this skill does
      placeholder: What does this skill do?
    validations:
      required: true
  
  - type: input
    id: author
    attributes:
      label: Author GitHub Username
      description: Your GitHub username (for credit)
      placeholder: e.g., steipete
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: The skill repository is public and contains a valid SKILL.md file
          required: true
        - label: I am the author or have permission to submit this skill
          required: true
